apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                   # [REQUIRED] Set to "true" if using managed identities
    keyvaultName: "abriggen3vault" # [REQUIRED] the name of the key vault
    cloudName: "" # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: "fence-creds"
          objectType: secret
          objectVersion: ""
        - |
          objectName: "ExamplePassword"
          objectType: secret
          objectVersion: ""
    resourceGroup: "abrig-gen3"
    subscriptionId: "7060bca0-7a3c-44bd-b54c-4bb1e9facfac"
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                 